from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


def _load_model_comparison(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(
            f"Model comparison JSON not found at {path}. Run real pipeline first."
        )
    return json.loads(path.read_text(encoding="utf-8"))


def _extract_model_metrics(model: dict, model_key: str) -> dict:
    nested_models = model.get("models", {}) if isinstance(model.get("models"), dict) else {}
    nested_block = nested_models.get(model_key, {}) if isinstance(nested_models.get(model_key), dict) else {}

    legacy_block = model.get(model_key, {}) if isinstance(model.get(model_key), dict) else {}

    chi2 = model.get(f"chi2_{model_key}")
    if chi2 is None:
        chi2 = nested_block.get("chi2", legacy_block.get("chi2"))

    aic = model.get(f"AIC_{model_key}")
    if aic is None:
        aic = nested_block.get("aic", nested_block.get("AIC", legacy_block.get("AIC", legacy_block.get("aic"))))

    bic = model.get(f"BIC_{model_key}")
    if bic is None:
        bic = nested_block.get("bic", nested_block.get("BIC", legacy_block.get("BIC", legacy_block.get("bic"))))

    return {
        "chi2": chi2,
        "AIC": aic,
        "BIC": bic,
    }


def _render_table(report: dict) -> str:
    rows = [
        ("RLL", report["rll"]),
        ("LCDM", report["lcdm"]),
    ]
    lines = [
        "# Model Comparison (Real Validation)",
        "",
        "| Model | chi2 | AIC | BIC | n_params | dataset | rerun_tolerance |",
        "|---|---:|---:|---:|---:|---|---|",
    ]
    for name, payload in rows:
        lines.append(
            f"| {name} | {payload['chi2']:.6f} | {payload['AIC']:.6f} | {payload['BIC']:.6f} | "
            f"{payload['n_params']} | {report['dataset']} | {report['rerun_tolerance']} |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Build real validation report artifacts")
    parser.add_argument(
        "--input-json",
        type=Path,
        default=Path("data/results/model_comparison.json"),
        help="Input model comparison JSON generated by the real pipeline",
    )
    parser.add_argument(
        "--out-json",
        type=Path,
        default=Path("results/real_validation_report.json"),
    )
    parser.add_argument(
        "--out-table",
        type=Path,
        default=Path("results/model_comparison_table.md"),
    )
    parser.add_argument(
        "--dataset",
        default="Pantheon+SH0ES",
    )
    parser.add_argument(
        "--rerun-tolerance",
        default="|ΔAIC|<=1e-6, |ΔBIC|<=1e-6, |Δχ²|<=1e-6",
    )
    args = parser.parse_args()

    model = _load_model_comparison(args.input_json)

    rll_metrics = _extract_model_metrics(model, "rll")
    lcdm_metrics = _extract_model_metrics(model, "lcdm")

    report = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "source": str(args.input_json),
        "dataset": args.dataset,
        "rerun_tolerance": args.rerun_tolerance,
        "n_obs": model["n_obs"],
        "k_rll": model.get("k_rll", 5),
        "k_lcdm": model.get("k_lcdm", 2),
        "delta_chi2_rll_minus_lcdm": model.get("delta_chi2_rll_minus_lcdm"),
        "delta_aic_rll_minus_lcdm": model.get("delta_aic_rll_minus_lcdm"),
        "delta_bic_rll_minus_lcdm": model.get("delta_bic_rll_minus_lcdm"),
        "interpretation_label": model.get("interpretation_label"),
        "claim_boundary": model.get(
            "claim_boundary",
            "No superiority claim unless real-data metrics pass predefined thresholds.",
        ),
        "rll": {
            "chi2": rll_metrics["chi2"],
            "AIC": rll_metrics["AIC"],
            "BIC": rll_metrics["BIC"],
            "n_params": model.get("k_rll", 5),
        },
        "lcdm": {
            "chi2": lcdm_metrics["chi2"],
            "AIC": lcdm_metrics["AIC"],
            "BIC": lcdm_metrics["BIC"],
            "n_params": model.get("k_lcdm", 2),
        },
    }

    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_table.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    args.out_table.write_text(_render_table(report), encoding="utf-8")


if __name__ == "__main__":
    main()
