from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


def _load_model_comparison(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(
            f"Model comparison JSON not found at {path}. Run real pipeline first."
        )
    return json.loads(path.read_text(encoding="utf-8"))


def _render_table(report: dict) -> str:
    rows = [
        ("RLL", report["rll"]),
        ("LCDM", report["lcdm"]),
    ]
    lines = [
        "# Model Comparison (Real Validation)",
        "",
        "| Model | chi2 | AIC | BIC | n_params | dataset | rerun_tolerance |",
        "|---|---:|---:|---:|---:|---|---|",
    ]
    for name, payload in rows:
        lines.append(
            f"| {name} | {payload['chi2']:.6f} | {payload['AIC']:.6f} | {payload['BIC']:.6f} | "
            f"{payload['n_params']} | {report['dataset']} | {report['rerun_tolerance']} |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Build real validation report artifacts")
    parser.add_argument(
        "--input-json",
        type=Path,
        default=Path("data/results/model_comparison.json"),
        help="Input model comparison JSON generated by the real pipeline",
    )
    parser.add_argument(
        "--out-json",
        type=Path,
        default=Path("results/real_validation_report.json"),
    )
    parser.add_argument(
        "--out-table",
        type=Path,
        default=Path("results/model_comparison_table.md"),
    )
    parser.add_argument(
        "--dataset",
        default="Pantheon+SH0ES",
    )
    parser.add_argument(
        "--rerun-tolerance",
        default="|ΔAIC|<=1e-6, |ΔBIC|<=1e-6, |Δχ²|<=1e-6",
    )
    args = parser.parse_args()

    model = _load_model_comparison(args.input_json)

    report = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "source": str(args.input_json),
        "dataset": args.dataset,
        "rerun_tolerance": args.rerun_tolerance,
        "n_obs": model["n_obs"],
        "rll": {
            "chi2": model["rll"]["chi2"],
            "AIC": model["rll"]["AIC"],
            "BIC": model["rll"]["BIC"],
            "n_params": 5,
        },
        "lcdm": {
            "chi2": model["lcdm"]["chi2"],
            "AIC": model["lcdm"]["AIC"],
            "BIC": model["lcdm"]["BIC"],
            "n_params": 2,
        },
    }

    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_table.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    args.out_table.write_text(_render_table(report), encoding="utf-8")


if __name__ == "__main__":
    main()
