#!/usr/bin/env bash
set -euo pipefail

# RLL real-data downloader
# Policy: download only from official/primary public sources. No synthetic data, no guessed covariance, no placeholder files.
# Usage:
#   bash scripts/download_real_cosmology_inputs.sh

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PANTHEON_DIR="$ROOT_DIR/data/pantheon"
REAL_DIR="$ROOT_DIR/data/real"
mkdir -p "$PANTHEON_DIR" "$REAL_DIR"

fetch() {
  local url="$1"
  local out="$2"
  local tmp="${out}.part"
  echo "[rll-download] fetching $url"
  if command -v curl >/dev/null 2>&1; then
    curl -fL --retry 3 --connect-timeout 30 "$url" -o "$tmp"
  elif command -v wget >/dev/null 2>&1; then
    wget -O "$tmp" "$url"
  else
    echo "[rll-download] ERROR: curl or wget is required" >&2
    exit 2
  fi
  test -s "$tmp"
  mv "$tmp" "$out"
}

sha256_one() {
  local path="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$path"
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$path"
  else
    python - "$path" <<'PY'
import hashlib, pathlib, sys
p = pathlib.Path(sys.argv[1])
h = hashlib.sha256()
with p.open('rb') as f:
    for chunk in iter(lambda: f.read(1024*1024), b''):
        h.update(chunk)
print(h.hexdigest(), p)
PY
  fi
}

# Official Pantheon+SH0ES data release repository:
# https://github.com/PantheonPlusSH0ES/DataRelease
# Directory documented by the collaboration:
# Pantheon+_Data/4_DISTANCES_AND_COVAR contains Pantheon+SH0ES.dat and Pantheon+SH0ES_STAT+SYS.cov.
PANTHEON_DAT_URL="https://raw.githubusercontent.com/PantheonPlusSH0ES/DataRelease/main/Pantheon%2B_Data/4_DISTANCES_AND_COVAR/Pantheon%2BSH0ES.dat"
PANTHEON_COV_URL="https://raw.githubusercontent.com/PantheonPlusSH0ES/DataRelease/main/Pantheon%2B_Data/4_DISTANCES_AND_COVAR/Pantheon%2BSH0ES_STAT%2BSYS.cov"

fetch "$PANTHEON_DAT_URL" "$PANTHEON_DIR/Pantheon+SH0ES.dat"
fetch "$PANTHEON_COV_URL" "$PANTHEON_DIR/Pantheon+SH0ES_STAT+SYS.cov"

# Compatibility for the current runner that historically expected this filename.
# This is a byte-for-byte copy of the official Pantheon+SH0ES.dat, not synthetic data.
cp "$PANTHEON_DIR/Pantheon+SH0ES.dat" "$PANTHEON_DIR/lcparam_full_long_zhel.txt"

MANIFEST="$REAL_DIR/downloaded_real_cosmology_inputs.sha256"
{
  echo "# Generated by scripts/download_real_cosmology_inputs.sh"
  echo "# Claim boundary: No superiority claim unless real-data metrics pass predefined thresholds."
  sha256_one "$PANTHEON_DIR/Pantheon+SH0ES.dat"
  sha256_one "$PANTHEON_DIR/Pantheon+SH0ES_STAT+SYS.cov"
  sha256_one "$PANTHEON_DIR/lcparam_full_long_zhel.txt"
} > "$MANIFEST"

cat > "$REAL_DIR/downloaded_real_cosmology_inputs.README.md" <<'MDEOF'
# Downloaded real cosmology inputs

This directory records local provenance for externally downloaded real-data files.

## Files downloaded by `scripts/download_real_cosmology_inputs.sh`

- `data/pantheon/Pantheon+SH0ES.dat`
- `data/pantheon/Pantheon+SH0ES_STAT+SYS.cov`
- `data/pantheon/lcparam_full_long_zhel.txt` — byte-for-byte compatibility copy of `Pantheon+SH0ES.dat` for the current runner.

## Source

Official public repository: `PantheonPlusSH0ES/DataRelease`.
The Pantheon+ directory documents that `Pantheon+_Data/4_DISTANCES_AND_COVAR` contains the nominal SN/Cepheid-host distances and the statistical plus systematic covariance matrix.

## Non-synthetic rule

No generated mock, guessed covariance, inferred BAO table, or placeholder file is accepted as real data.
Missing data must remain a declared lacuna until an official source is materialized.
MDEOF

echo "[rll-download] wrote $MANIFEST"
echo "[rll-download] next: python scripts/run_real_pantheon_validation.py"
