#!/usr/bin/env python3
"""Generate the H0/r_d ablation matrix required by RLL issue #423.

This tool does not pretend to execute a cosmology fit. It creates the auditable
run matrix that the likelihood pipeline must consume so every H0/r_d policy is
explicit, comparable and machine-readable.
"""

from __future__ import annotations

import argparse
import csv
import json
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Literal

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_JSON = ROOT / "data" / "inputs" / "cosmology_joint" / "h0_rd_ablation_matrix.json"
DEFAULT_CSV = ROOT / "data" / "inputs" / "cosmology_joint" / "h0_rd_ablation_matrix.csv"
DEFAULT_MD = ROOT / "docs" / "RLL_H0_RD_ABLATION_MATRIX.md"

H0Policy = Literal["broad_free", "planck_prior", "shoes_local_prior"]
RdPolicy = Literal["fixed_for_all", "derived_for_all"]


@dataclass(frozen=True)
class AblationRun:
    run_id: str
    H0_policy: H0Policy
    H0_prior_label: str
    H0_prior_mean: float | None
    H0_prior_sigma: float | None
    H0_bounds: str
    rd_policy: RdPolicy
    rd_fixed_value_mpc: float | None
    models_required: str
    covariance_policy: str
    expected_output_columns: str
    claim_boundary: str
    command_template: str


def build_matrix() -> list[AblationRun]:
    h0_policies: list[tuple[H0Policy, str, float | None, float | None, str]] = [
        ("broad_free", "broad/free/no_external_H0_prior", None, None, "50..90"),
        ("planck_prior", "Planck2018", 67.4, 0.5, "50..90"),
        ("shoes_local_prior", "SH0ES_local_distance_ladder", 73.04, 1.04, "50..90"),
    ]
    rd_policies: list[tuple[RdPolicy, float | None]] = [
        ("fixed_for_all", 147.78),
        ("derived_for_all", None),
    ]

    runs: list[AblationRun] = []
    for h0_policy, h0_label, h0_mean, h0_sigma, h0_bounds in h0_policies:
        for rd_policy, rd_fixed in rd_policies:
            run_id = f"h0_{h0_policy}__rd_{rd_policy}"
            runs.append(
                AblationRun(
                    run_id=run_id,
                    H0_policy=h0_policy,
                    H0_prior_label=h0_label,
                    H0_prior_mean=h0_mean,
                    H0_prior_sigma=h0_sigma,
                    H0_bounds=h0_bounds,
                    rd_policy=rd_policy,
                    rd_fixed_value_mpc=rd_fixed,
                    models_required="LCDM,wCDM,CPL,RLL",
                    covariance_policy="same_vector_same_covariance_for_all_models",
                    expected_output_columns="model,chi2,AIC,AICc,BIC,N,k,dof,H0_policy,rd_policy,H0,rd,Os0,Delta_AICc_RLL_CPL,Delta_BIC_RLL_CPL,claim_status",
                    claim_boundary="sensitivity_only_until_covariance_MCMC_and_CLASS_CAMB_gates_are_satisfied",
                    command_template=(
                        "python3 tools/run_rll_academic_claim_governance.py "
                        f"--input results/structure_d/ablation/{run_id}.csv"
                    ),
                )
            )
    return runs


def write_json(runs: list[AblationRun], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "schema": "rll.h0_rd_ablation_matrix.v1",
        "purpose": "Declare the H0/r_d sensitivity runs required before strong RLL claims.",
        "runs": [asdict(run) for run in runs],
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_csv(runs: list[AblationRun], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    rows = [asdict(run) for run in runs]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def write_markdown(runs: list[AblationRun], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    lines.append("# RLL H0/r_d Ablation Matrix")
    lines.append("")
    lines.append("> Auto-generated by `tools/make_h0_rd_ablation_matrix.py`.")
    lines.append("")
    lines.append("## Purpose")
    lines.append("")
    lines.append("This matrix makes H0 and r_d policy explicit before interpreting RLL against CPL/w0waCDM.")
    lines.append("")
    lines.append("## Runs")
    lines.append("")
    lines.append("| run_id | H0_policy | H0_prior | rd_policy | rd_fixed_value_mpc | claim_boundary |")
    lines.append("|---|---|---|---|---:|---|")
    for run in runs:
        rd_value = "TOKEN_VAZIO" if run.rd_fixed_value_mpc is None else f"{run.rd_fixed_value_mpc:g}"
        lines.append(
            f"| `{run.run_id}` | {run.H0_policy} | {run.H0_prior_label} | {run.rd_policy} | {rd_value} | {run.claim_boundary} |"
        )
    lines.append("")
    lines.append("## Required interpretation")
    lines.append("")
    lines.append("Every run must be rescanned by `tools/scan_rll_model_evidence.py`. If Os0 remains zero and CPL remains best by AICc/BIC, the negative RLL result is more stable. If RLL improves only under one policy, the conclusion is sensitivity-dependent, not proof.")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the RLL H0/r_d ablation matrix.")
    parser.add_argument("--json-out", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--csv-out", type=Path, default=DEFAULT_CSV)
    parser.add_argument("--md-out", type=Path, default=DEFAULT_MD)
    parser.add_argument("--no-write", action="store_true")
    args = parser.parse_args()

    runs = build_matrix()
    if not args.no_write:
        write_json(runs, args.json_out)
        write_csv(runs, args.csv_out)
        write_markdown(runs, args.md_out)
        print(f"wrote: {args.json_out}")
        print(f"wrote: {args.csv_out}")
        print(f"wrote: {args.md_out}")
    print(f"PASS: generated {len(runs)} H0/r_d ablation policy rows")


if __name__ == "__main__":
    main()
