#!/usr/bin/env python3
"""Run the integrated RLL academic-governance gate.

This wrapper connects the two required audit surfaces:

1. parameter provenance and academic registry validation;
2. calculable evidence scanning from the current result table.

It then emits a compact Markdown gate report that downstream reports can import
instead of making free-text claims.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "results" / "structure_d" / "joint_real_likelihood.csv"
DEFAULT_REGISTRY = ROOT / "data" / "inputs" / "cosmology_joint" / "parameter_origin_registry.json"
DEFAULT_JSON = ROOT / "results" / "audit" / "rll_model_evidence_scan.json"
DEFAULT_MD = ROOT / "results" / "audit" / "rll_model_evidence_scan.md"
DEFAULT_GATE_REPORT = ROOT / "results" / "audit" / "rll_academic_claim_gate_report.md"


def run_cmd(cmd: list[str]) -> None:
    print("+ " + " ".join(cmd))
    proc = subprocess.run(cmd, cwd=ROOT, text=True)
    if proc.returncode != 0:
        raise SystemExit(proc.returncode)


def load_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise SystemExit(f"FAIL: expected JSON output not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise SystemExit(f"FAIL: invalid scan JSON: {path}: {exc}") from exc


def fmt(value: Any) -> str:
    if value is None:
        return "TOKEN_VAZIO"
    if isinstance(value, float):
        return f"{value:.6g}"
    return str(value)


def find_rll_scan(scan: dict[str, Any]) -> dict[str, Any] | None:
    for row in scan.get("model_scans", []):
        if row.get("model") == "RLL":
            return row
    return None


def write_gate_report(scan: dict[str, Any], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    rll = find_rll_scan(scan)
    lines: list[str] = []
    lines.append("# RLL Academic Claim Gate Report")
    lines.append("")
    lines.append("> Auto-generated by `tools/run_rll_academic_claim_governance.py`.")
    lines.append("")
    lines.append("## Gate summary")
    lines.append("")
    lines.append(f"- claim_status: **{fmt(scan.get('claim_status'))}**")
    lines.append(f"- claim_summary: {fmt(scan.get('claim_summary'))}")
    lines.append(f"- registry_schema: `{fmt(scan.get('registry_schema'))}`")
    lines.append(f"- input_csv: `{fmt(scan.get('input_csv'))}`")
    lines.append(f"- commit_sha: `{fmt(scan.get('commit_sha'))}`")
    lines.append(f"- best_by_AICc: `{fmt(scan.get('best_by_AICc'))}`")
    lines.append(f"- best_by_BIC: `{fmt(scan.get('best_by_BIC'))}`")
    lines.append(f"- H0_all_equal: `{fmt(scan.get('H0_all_equal'))}`")
    lines.append("")

    lines.append("## RLL vs CPL")
    lines.append("")
    if rll is None:
        lines.append("TOKEN_VAZIO: no RLL row found in evidence scan.")
    else:
        lines.append(f"- Delta AICc RLL-CPL: `{fmt(rll.get('delta_AICc_CPL'))}`")
        lines.append(f"- Delta BIC RLL-CPL: `{fmt(rll.get('delta_BIC_CPL'))}`")
        lines.append(f"- Os0: `{fmt(rll.get('Os0'))}`")
        lines.append(f"- zt: `{fmt(rll.get('zt'))}`")
        lines.append(f"- wt: `{fmt(rll.get('wt'))}`")
        flags = rll.get("local_flags") or []
        if flags:
            lines.append("- local_flags:")
            for flag in flags:
                lines.append(f"  - {flag}")
    lines.append("")

    blocking = scan.get("blocking_reasons") or []
    warnings = scan.get("warnings") or []
    if blocking:
        lines.append("## Blocking reasons")
        lines.append("")
        for reason in blocking:
            lines.append(f"- {reason}")
        lines.append("")
    if warnings:
        lines.append("## Warnings")
        lines.append("")
        for warning in warnings:
            lines.append(f"- {warning}")
        lines.append("")

    lines.append("## Allowed wording")
    lines.append("")
    if scan.get("claim_status") == "PASS_LIMITED":
        lines.append("RLL is not worse than CPL in this result table by the scanned criteria, but the claim remains limited until covariance, priors, MCMC and Boltzmann/growth gates are satisfied.")
    elif scan.get("claim_status") == "CLAIM_BLOCKED":
        lines.append("Nesta rodada, o scanner bloqueia claim positivo. Relatórios devem explicar o bloqueio e não devem dizer que RLL vence, prova ou faz melhor aos dados.")
    else:
        lines.append("Resultado parcial: relatar limitações antes de qualquer interpretação positiva.")
    lines.append("")

    lines.append("## Machine contract")
    lines.append("")
    lines.append("Generated reports should import this gate report or the JSON scan before writing scientific claims.")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Run RLL academic claim governance.")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    parser.add_argument("--json-out", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--md-out", type=Path, default=DEFAULT_MD)
    parser.add_argument("--gate-report", type=Path, default=DEFAULT_GATE_REPORT)
    parser.add_argument("--no-write", action="store_true", help="Run validation and scanner without writing reports")
    parser.add_argument("--fail-on-blocked", action="store_true", help="Exit non-zero when claim_status is CLAIM_BLOCKED")
    args = parser.parse_args()

    run_cmd([sys.executable, "tools/validate_academic_parameter_registry.py"])

    scan_cmd = [
        sys.executable,
        "tools/scan_rll_model_evidence.py",
        "--input",
        str(args.input),
        "--registry",
        str(args.registry),
        "--json-out",
        str(args.json_out),
        "--md-out",
        str(args.md_out),
    ]
    if args.no_write:
        scan_cmd.append("--no-write")
    run_cmd(scan_cmd)

    if args.no_write:
        return

    scan = load_json(args.json_out)
    write_gate_report(scan, args.gate_report)
    print(f"wrote: {args.gate_report}")

    if args.fail_on_blocked and scan.get("claim_status") == "CLAIM_BLOCKED":
        raise SystemExit("FAIL: claim_status=CLAIM_BLOCKED")


if __name__ == "__main__":
    main()
